spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/db_raizes_nordeste
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
